version: '3'

services:

  enroll-php-fpm:
    container_name: enroll-php-fpm
    restart: always
    image: ${REGISTRY}:demo-php-fpm-${IMAGE_TAG}
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: pgsql://app:${POSTGRES_PASSWORD}@enroll-db:5432/${POSTGRES_DB}
      MAILER_DSN: ${MAILER_DSN}
      MAILER_SENDER: ${MAILER_SENDER}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - enroll-db

  enroll-db:
    container_name: enroll-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: ${REGISTRY}:demo-db-${IMAGE_TAG}
    volumes:
      - enroll-db:/var/lib/postgresql/data:rw

  enroll-nginx:
    container_name: enroll-nginx
    restart: always
    image: ${REGISTRY}:demo-nginx-${IMAGE_TAG}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - enroll-php-fpm
    ports:
      - "80:80"
      - "443:443"

volumes:
  enroll-db:
