version: '3.8'
services:

  test-enroll-php-fpm:
    container_name: test-enroll-php-fpm
    build:
      context: app/.docker/test/
      dockerfile: php-fpm.docker
    env_file:
      - app/.env.test
    volumes:
      - ./app:/app
      - test-build:/app/public/build/
    depends_on:
      - test-enroll-db

  test-enroll-db:
    container_name: test-enroll-db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secrect
    volumes:
      - test-enroll-db:/var/lib/postgresql/data:rw
    build:
      context: app/.docker/test/
      dockerfile: db.docker

  test-enroll-nginx:
    container_name: test-enroll-nginx
    build:
      context: app/.docker/test/
      dockerfile: nginx.docker
    volumes:
      - ./app:/app
      - test-build:/app/public/build/
    depends_on:
      test-enroll-php-fpm:
        condition: service_started
      test-enroll-front-watcher:
        condition: service_healthy

  test-enroll-mailer:
    image: mailhog/mailhog

  test-enroll-front-watcher:
    container_name: test-enroll-front-watcher
    image: node:19.8-alpine3.17
    working_dir: /app
    volumes:
      - ./app:/app
      - test-build:/app/public/build/
      - enrollment-demo-app_node-cache:/usr/local/share/.cache
    command: sh -c "rm -rf /app/public/build/*; yarn install; yarn watch"
    healthcheck:
      test: [ "CMD-SHELL", "test -f /app/public/build/manifest.json" ]
      interval: 2s
      retries: 500
    tty: true

  test-enroll-selenium:
    image: selenium/standalone-firefox:4.12.1-20230904
    shm_size: 2gb
    ports:
      # to watch what's happening inside browser while tests running
      # http://localhost:7900/?autoconnect=1&resize=scale&password=secret
      - "7900:7900"
    environment:
      # when a test fails, its connection will be closed by selenium in 30 seconds
      # also if a test doesn't send any commands in 30sec, its connection will be closed by selenium
      SE_NODE_SESSION_TIMEOUT: 30
      # to be able to run another test after one fails (with hanging still open connection)
      # we need to increase the number of sessions
      SE_NODE_MAX_SESSIONS: 10
      SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
      # for CI should be false
      START_XVFB: 'false'

volumes:
  enrollment-demo-app_node-cache:
    external: true
  test-build:
  test-enroll-db: