version: '3'

services:

  enroll-php-fpm:
    container_name: enroll-php-fpm
    image: ${REGISTRY}:demo-php-fpm-${IMAGE_TAG}
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: pgsql://app:${POSTGRES_PASSWORD}@enroll-app-db:5432/${POSTGRES_DB}
      MAILER_DSN: ${MAILER_DSN}
      MAILER_SENDER: ${MAILER_SENDER}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - enroll-app-db

  enroll-app-db:
    container_name: enroll-app-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: ${REGISTRY}:demo-db-${IMAGE_TAG}
    volumes:
      - enroll-db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  enroll-nginx:
    container_name: enroll-app-nginx
    image: ${REGISTRY}:demo-nginx-${IMAGE_TAG}
    depends_on:
      - enroll-php-fpm
    ports:
      - "80:80"

volumes:
  enroll-db: