version: '3.8'
name: test-enroll
services:

  test-enroll-php-fpm:
    container_name: test-enroll-php-fpm
    networks:
      - test-enroll
    build:
      context: app/.docker/test/
      dockerfile: php-fpm.docker
    env_file:
      - app/.env.test
    volumes:
      - ./app:/app
      - test-build:/app/public/build/
    depends_on:
      - test-enroll-db

  test-enroll-db:
    container_name: test-enroll-db
    networks:
      - test-enroll
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secrect
    build:
      context: app/.docker/test/
      dockerfile: db.docker
    volumes:
      - test-enroll-db:/var/lib/postgresql/data:rw

  test-enroll-nginx:
    container_name: test-enroll-nginx
    networks:
      - test-enroll
    build:
      context: app/.docker/test/
      dockerfile: nginx.docker
    volumes:
      - ./app:/app
      - test-build:/app/public/build/
    depends_on:
      test-enroll-php-fpm:
        condition: service_started
      test-enroll-front-watcher:
        condition: service_healthy

  test-enroll-mailer:
    image: mailhog/mailhog
    networks:
      - test-enroll

  test-enroll-front-watcher:
    container_name: test-enroll-front-watcher
    image: node:19.8-alpine3.17
    networks:
      - test-enroll
    working_dir: /app
    volumes:
      - ./app:/app
      - test-build:/app/public/build/
      - enrollment-demo-app_node-cache:/usr/local/share/.cache
    command: sh -c "yarn watch"
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/public/build/manifest.json"]
      interval: 2s
      retries: 60
    tty: true

  test-enroll-selenium:
    image: selenium/standalone-chrome
    networks:
      - test-enroll

volumes:
  enrollment-demo-app_node-cache:
    external: true
  test-enroll-db:
  test-build:

networks:
  test-enroll: