version: '3.8'

services:

  enroll-php-fpm:
    image: ${REGISTRY}:demo-php-fpm-${IMAGE_TAG}
    container_name: enroll-php-fpm
    restart: always
    environment:
      APP_ENV: test
      APP_DEBUG: 0
      DATABASE_URL: pgsql://app:secrect@enroll-db:5432/app
    volumes:
      - ./app/tests:/app/tests
      - ./app/vendor:/app/vendor
      - ./app/node_modules:/app/node_modules
      - ./app/codeception.yml:/app/codeception.yml
    depends_on:
      - enroll-db
      - test-enroll-selenium

  enroll-db:
    image: postgres:15-alpine
    container_name: enroll-db
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secrect

  test-enroll-nginx:
    image: ${REGISTRY}:demo-nginx-${IMAGE_TAG}
    container_name: test-enroll-nginx
    restart: always
    volumes:
      - ./app/vendor:/app/vendor
      - ./app/node_modules:/app/node_modules
    depends_on:
      - enroll-php-fpm

  test-enroll-selenium:
    image: selenium/standalone-firefox:4.12.1-20230904
    shm_size: 2gb
    environment:
      # for CI should be false
      START_XVFB: 'false'

  test-enroll-mail:
    image: mailhog/mailhog
    container_name: test-enroll-mail
