version: '3'

services:

  enroll-php-fpm:
    container_name: enroll-php-fpm
    restart: always
    image: ${REGISTRY}:demo-php-fpm-${IMAGE_TAG}
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: pgsql://app:${POSTGRES_PASSWORD}@enroll-db:5432/${POSTGRES_DB}
      MAILER_DSN: ${MAILER_DSN}
      MAILER_SENDER: ${MAILER_SENDER}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - enroll-db

  enroll-db:
    container_name: enroll-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: ${REGISTRY}:demo-db-${IMAGE_TAG}
    volumes:
      - enroll-db:/var/lib/postgresql/data:rw

  enroll-nginx:
    container_name: enroll-nginx
    restart: always
    image: ${REGISTRY}:demo-nginx-${IMAGE_TAG}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - enroll-php-fpm
    ports:
      - "80:80"
      - "443:443"

  enroll-mail:
    image: mailserver/docker-mailserver:12.1.0
    container_name: enroll-mail
    hostname: aborzenko.com
    env_file: .env.mail
    ports:
      - "25:25"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

volumes:
  enroll-db:
