version: '3'

services:

  enroll-php-fpm:
    container_name: enroll-php-fpm
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    build:
      context: app/.docker/dev/
      dockerfile: php-fpm.docker
    volumes:
      - ./app:/app
    depends_on:
      - enroll-db

  enroll-db:
    container_name: enroll-db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secrect
    build:
      context: app/.docker/dev/
      dockerfile: db.docker
    volumes:
      - ./app:/app
      - enroll-db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  enroll-nginx:
    container_name: enroll-nginx
    build:
      context: app/.docker/dev/
      dockerfile: nginx.docker
    volumes:
      - ./app:/app
    depends_on:
      enroll-php-fpm:
        condition: service_started
      enroll-front-node:
        condition: service_healthy
    ports:
      - "8080:80"

  enroll-mailer:
    image: mailhog/mailhog
    ports:
      - "8082:8025"

  enroll-node:
    image: node:19.8-alpine3.17
    volumes:
      - ./app:/app
      - node-cache:/usr/local/share/.cache
    working_dir: /app

  enroll-front-node:
    image: node:19.8-alpine3.17
    working_dir: /app
    environment:
      WDS_SOCKET_PORT: 0
    volumes:
      - ./app:/app
      - node-cache:/usr/local/share/.cache
    command: sh -c "yarn dev-server --hot --port 8080 --host 0.0.0.0"
    healthcheck:
      test: sh -c "wget http://0.0.0.0:8080/build/runtime.js --spider"
      interval: 2s
      retries: 60
    tty: true

volumes:
  enroll-db:
  node-cache:
