# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # admin
    App\Security\Admin\AdminDbHelper:
        arguments:
            $entityClassName: App\Domain\Admin\Entity\AdminUser\AdminUser

    App\Security\Admin\AdminProvider:
        arguments:
            App\Security\AbstractUserDbHelper: '@App\Security\Admin\AdminDbHelper'
            $userClassName: App\Security\Admin\AdminReadModel

    App\Security\Admin\AdminAuthenticator:
        arguments:
            App\Security\AbstractUserProvider: '@App\Security\Admin\AdminProvider'

    # student
    App\Security\Student\StudentDbHelper:
        arguments:
            $entityClassName: App\Domain\Student\Entity\Student\Student

    App\Security\Student\StudentProvider:
        arguments:
            App\Security\AbstractUserDbHelper: '@App\Security\Student\StudentDbHelper'
            $userClassName: App\Security\Student\StudentReadModel

    App\Security\Student\StudentAuthenticator:
        arguments:
            App\Security\AbstractUserProvider: '@App\Security\Student\StudentProvider'

    # school
    App\Security\School\SchoolStaffMemberDbHelper:
        arguments:
            $entityClassName: App\Domain\School\Entity\School\StaffMember

    App\Security\School\SchoolStaffMemberProvider:
        arguments:
            App\Security\AbstractUserDbHelper: '@App\Security\School\SchoolStaffMemberDbHelper'
            $userClassName: App\Security\School\SchoolStaffMemberReadModel

    App\Security\School\SchoolStaffMemberAuthenticator:
        arguments:
            App\Security\AbstractUserProvider: '@App\Security\School\SchoolStaffMemberProvider'

