<?php

declare(strict_types=1);

namespace App\DbDefaultData;

use App\Core\Common\UuidGenerator;
use App\Core\School\Entity\Campus\Campus;
use App\Core\School\Entity\Campus\CampusId;
use App\Core\School\Entity\Course\Course;
use App\Core\School\Entity\Course\CourseId;
use App\Core\School\Entity\Course\Intake\IntakeId;
use App\Core\School\Entity\School\Email;
use App\Core\School\Entity\School\InvitationToken;
use App\Core\School\Entity\School\Name;
use App\Core\School\Entity\School\School;
use App\Core\School\Entity\School\SchoolId;
use App\Core\School\Entity\School\StaffMember;
use App\Core\School\Entity\School\StaffMemberId;
use App\Core\School\Entity\School\StaffMemberName;
use App\Core\Student\Entity\Application\Application;
use App\Core\Student\Entity\Application\ApplicationId;
use Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface;

class SchoolDataCreator
{
    private const SCHOOL_NAMES = [
        'Evergreen University',
        'Stellar Institute of Technology',
        'Cascade University',
        'Phoenix University',
        'Horizon College',
        'Emerald State University',
        'Celestial Academy',
        'Silverwood College',
        'Oceanview Institute',
        'Crimson Peak University',
        'Radiant Polytechnic Institute',
        'Harmony University',
        'Serene Academy of Arts',
        'Thunderbird College',
        'Golden Gate University',
        'Tranquil University',
        'Beacon Hill College',
        'Sparkling Waters Institute',
        'Misty Mountains College',
        'Liberty University',
        'Sunrise Institute of Science',
        'Moonlight College',
        'Crystal Valley University',
        'North Star Academy',
        'Willowbrook College',
        'Springdale University',
        'Solaris Institute',
        'Cascade Falls College',
        'Ivy League University',
        'Harmony Hills College',
        'Rising Sun Institute',
        'Starlight University',
        'Horizon Bay College',
        'Whispering Pines Academy',
        'Glacier State University',
        'Serendipity College',
        'Paradise Valley Institute',
        'Lighthouse University',
        'Zenith Academy',
        'Alpine Meadows College',
        'Firefly University',
        'Ocean Breeze Institute',
        'Radiant City College',
        'Horizon View University',
        'Moonshadow Academy',
        'Silverlake College',
        'Enchanted Woods Institute',
        'Aurora University',
        'Solstice College',
        'Willowbrook Academy',
        'Coastal Bay University',
        'Ember Institute of Technology',
        'Sapphire Hills College',
        'Tranquil Shores University',
        'Radiant Skies College',
        'Whispering Winds University',
        'Stellar City College',
        'Cascade Pines Academy',
        'Celestial Heights University',
        'Luminous College',
        'Sunflower Institute',
        'Riverbend University',
        'Silverstone College',
        'Alpine Summit University',
        'Stardust Academy',
        'Harmony Springs College',
        'Beacon View Institute',
        'Serene Shores University',
        'Zenith Heights College',
        'Thunder Peak University',
        'Cascade Valley College',
        'Golden Oaks Institute',
        'Horizon Crest University',
        'Emberwood College',
        'Starlight Shores University',
        'Moonlit Academy',
        'Sapphire State College',
        'Radiant Glade University',
        'Oceanfront Institute',
        'Whispering Brook College',
        'Alpine Ridge University',
        'Tranquil Gardens College',
        'Aurora Bay Institute',
        'Willowgate University',
        'Cascade Heights College',
        'Horizon Meadows Academy',
        'Luminous City College',
        'Celestial Gardens University',
        'Sunburst College',
        'Beacon Hills Institute',
        'Serenity Shores University',
        'Zenith View College',
        'Thunder Valley University',
        'Silverleaf College',
        'Radiant Waters Institute',
        'Oceanic Academy',
        'Whispering Vale College',
        'Skyline University',
        'Everlasting Institute',
    ];
    private const ADMIN_NAMES = [
        'Amelia Anderson',
        'Benjamin Carter',
        'Charlotte Davis',
        'Daniel Evans',
        'Emma Fisher',
        'Gabriel Green',
        'Hannah Harris',
        'Isaac Jackson',
        'Jessica Kelly',
        'Lucas Lewis',
        'Madison Morgan',
        'Noah Nelson',
        'Olivia Owens',
        'Peter Patel',
        'Rachel Robinson',
        'Samuel Scott',
        'Taylor Turner',
        'Victoria Walker',
        'William White',
        'Zoe Young',
        'Alexander Bailey',
        'Brooke Bennett',
        'Caleb Clark',
        'Delilah Dixon',
        'Ethan Edwards',
        'Faith Foster',
        'Grace Gray',
        'Hayden Hayes',
        'Isabella Inman',
        'Jack Johnson',
        'Kaitlyn King',
        'Liam Lopez',
        'Mia Mitchell',
        'Nathan Nguyen',
        'Olivia Neill',
        'Paige Porter',
        'Quentin Quinn',
        'Ruby Rivera',
        'Sophia Sullivan',
        'Tyler Thompson',
        'Ulysses Underwood',
        'Vanessa Vasquez',
        'Wyatt Warren',
        'Xavier Xu',
        'Yara Yates',
        'Zachary Zimmerman',
        'Abigail Abbott',
        'Brandon Brooks',
        'Chloe Collins',
        'David Douglas',
        'Emily Ellis',
        'Finnegan Ford',
        'Georgia Gonzalez',
        'Henry Hudson',
        'Isla Ibarra',
        'Jacob Jenkins',
        'Kennedy Kim',
        'Lily Lawson',
        'Mason Murphy',
        'Natalie Newton',
        'Oliver O\'Connor',
        'Penelope Peterson',
        'Quentin Quintana',
        'Riley Ross',
        'Savannah Smith',
        'Timothy Taylor',
        'Ursula Underhill',
        'Vivian Vargas',
        'Wesley Wells',
        'Xander Xavier',
        'Yasmine York',
        'Zane Ziegler',
        'Amelia Adams',
        'Benjamin Black',
        'Charlotte Cooper',
        'Daniel Donovan',
        'Emma Evers',
        'Gabriel Garcia',
        'Hannah Hughes',
        'Isaac Ingram',
        'Jessica James',
        'Lucas Lee',
        'Madison Martinez',
        'Noah Nixon',
        'Olivia Ortiz',
        'Peter Price',
        'Rachel Reed',
        'Samuel Sanchez',
        'Taylor Thomas',
        'Victoria Vega',
        'William Wallace',
        'Zoe Zimmerman',
        'Olivia Bennett',
        'Ethan Carter',
        'Isabella Diaz',
        'Lucas Evans',
        'Ava Gray',
        'Noah Hernandez',
        'Mia Jenkins',
        'Liam Martinez',
    ];
    private const CAMPUSES_NAMES = [
        'Willowbrook Plaza Campus',
        'Starlight Campus',
        'Cascade Valley Campus',
        'Phoenix Summit Campus',
        'Horizon Bay Campus',
        'Emerald Meadows Campus',
        'Celestial View Campus',
        'Silverwood Ridge Campus',
        'Oceanview Point Campus',
        'Crimson Peak Campus',
        'Radiant Campus',
        'Harmony Hills Campus',
        'Serene Shores Campus',
        'Thunderbird Bluff Campus',
        'Golden Gate Campus',
        'Tranquil Gardens Campus',
        'Beacon Hill Campus',
        'Sparkling Waters Campus',
        'Skyline Terrace Campus',
        'Misty Mountains Campus',
        'Liberty Square Campus',
        'Sunrise Plaza Campus',
        'Moonlight Crest Campus',
        'Crystal Valley Campus',
        'North Star Campus',
        'Willowbrook Commons Campus',
        'Springdale Plaza Campus',
        'Solaris Heights Campus',
        'Cascade Falls Campus',
        'Ivy League Campus',
        'Harmony Springs Campus',
        'Rising Sun Campus',
        'Starlight Square Campus',
        'Horizon Crest Campus',
        'Whispering Pines Campus',
        'Glacier State Campus',
        'Serendipity Gardens Campus',
        'Paradise Valley Campus',
        'Lighthouse Bay Campus',
        'Zenith Square Campus',
        'Alpine Meadows Campus',
        'Firefly Ridge Campus',
        'Ocean Breeze Campus',
        'Radiant City Campus',
        'Horizon View Campus',
        'Moonshadow Terrace Campus',
        'Silverlake Heights Campus',
        'Enchanted Woods Campus',
        'Aurora Terrace Campus',
        'Solstice Grove Campus',
        'Tranquil Bluff Campus',
        'Stardust Campus',
        'Radiant Bay Campus',
        'Serene Summit Campus',
        'Whispering Brookside Campus',
        'Celestial Oasis Campus',
        'Silverwood Glade Campus',
        'Emerald Crest Campus',
        'Terrace Campus',
        'Cascade Meadows Campus',
        'Harmony Haven Campus',
        'Crimson Campus',
        'Phoenix Waterside Campus',
        'Tranquil Ridge Campus',
        'Oceanview Glade Campus',
        'Radiant Point Campus',
        'Gardens Campus',
        'Thunderbird Springs Campus',
        'Beacon Hilltop Campus',
        'Skyline Haven Campus',
        'Lighthouse Terrace Campus',
        'Sapphire Meadows Campus',
        'Moonlight Summit Campus',
        'Golden Valley Campus',
        'Misty Brookside Campus',
        'Ivy League Plaza Campus',
        'Serendipity Bluff Campus',
        'Horizon Campus',
        'Whispering Ridge Campus',
        'Radiant Heights Campus',
        'Solaris View Campus',
        'Springdale Haven Campus',
        'Ocean Breeze Terrace Campus',
        'Celestial Bay Campus',
        'Harmony Brookside Campus',
        'Aurora Meadows Campus',
        'Silverlake Summit Campus',
        'Emerald Springs Campus',
        'Tranquil Crest Campus',
        'Stardust Terrace Campus',
        'Radiant Meadows Campus',
        'Serene Shoreside Campus',
        'Willowbrook View Campus',
        'Thunderbird Haven Campus',
        'Starlight Meadows Campus',
        'Cascade Point Campus',
        'Celestial Ridge Campus',
        'Horizon Glade Campus',
        'Whisper Campus',
        'Golden Heights Campus',
        'Oceanview Plaza Campus',
        'Crimson Terrace Campus',
        'Silverwood Gardens Campus',
        'Ivy Campus',
        'Radiant Square Campus',
        'Tranquil Meadows Campus',
        'Hillside Campus',
        'Serendipity Summit Campus',
        'Horizon Waterside Campus',
        'Moonlight Haven Campus',
        'Solaris Viewpoint Campus',
        'Emerald Shores Campus',
        'Harmony Ridge Campus',
        'Ocean Breeze Meadows Campus',
        'Radiant Brookside Campus',
        'Willowbrook Glade Campus',
        'Starlight Heights Campus',
        'Thunderbird Crest Campus',
        'Whispering Terrace Campus',
        'Center Campus',
        'Silverwood Summit Campus',
        'Ivy League Bluff Campus',
        'Cascade View Campus',
        'Serene Haven Campus',
        'Horizon Brookside Campus',
        'Radiant Terrace Campus',
        'Tranquil Bay Campus',
        'Oceanview Crest Campus',
        'Stardust Heights Campus',
        'Beacon Hillside Campus',
        'Golden Meadows Campus',
        'Moonlight Oasis Campus',
        'Willowbrook Gardens Campus',
        'Solaris Ridge Campus',
        'Crimson Plaza Campus',
        'Silverwood Terrace Campus',
        'Whispering Summit Campus',
        'Serendipity Haven Campus',
        'Harmony Bluff Campus',
        'Radiant Glade Campus',
        'Celestial Valley Campus',
        'Ivy League Meadows Campus',
        'Cascade Brookside Campus',
        'Oceanview Heights Campus',
        'Starlight Terrace Campus',
        'Horizon Summit Campus',
        'Tranquil Waterside Campus',
        'Stardust Ridge Campus',
        'Willowbrook Haven Campus',
        'Thunderbird Bay Campus',
    ];
    private const COURSES = [
        'Bachelor of Computer Science',
        'Master of Electrical Engineering',
        'Bachelor of English Literature',
        'Bachelor of Science in Psychology',
        'Bachelor of Business Administration',
        'Bachelor of Science in Biology',
        'Bachelor of Science in Mathematics',
        'Bachelor of Arts in History',
        'Bachelor of Science in Marketing',
        'Bachelor of Science in Environmental Science',
        'Bachelor of Arts in Economics',
        'Bachelor of Arts in Sociology',
        'Bachelor of Arts in Journalism',
        'Bachelor of Arts in Political Science',
        'Bachelor of Science in Chemistry',
        'Bachelor of Education',
        'Bachelor of Science in Finance',
        'Bachelor of Fine Arts in Graphic Design',
        'Bachelor of Architecture',
        'Bachelor of Arts in Communication Studies',
        'Bachelor of Arts in Linguistics',
        'Bachelor of Arts in Anthropology',
        'Bachelor of Arts in International Relations',
        'Bachelor of Science in Physics',
        'Bachelor of Science in Nursing',
        'Bachelor of Arts in Philosophy',
        'Bachelor of Science in Human Resource Management',
        'Master of Industrial Engineering',
        'Bachelor of Arts in Art History',
        'Bachelor of Science in Public Health',
        'Bachelor of Science in Information Technology',
        'Bachelor of Arts in Media Studies',
        'Bachelor of Fine Arts in Theater Arts',
        'Bachelor of Science in Criminal Justice',
        'Bachelor of Arts in Geography',
        'Bachelor of Music',
        'Bachelor of Science in Hospitality Management',
        'Bachelor of Social Work',
        'Bachelor of Urban Planning',
        'Bachelor of Science in Nutrition and Dietetics',
        'Bachelor of Science in Economics and Finance',
        'Bachelor of Science in Biomedical Engineering',
        'Bachelor of Psychology',
        'Bachelor of Arts in Creative Writing',
        'Bachelor of Science in Computer Engineering',
        'Bachelor of Arts in International Business',
        'Bachelor of Science in Environmental Engineering',
        'Bachelor of Sociology',
        'Bachelor of Arts in Media Production',
        'Bachelor of Political Science',
        'Bachelor of Science in Biochemistry',
        'Bachelor of Social Sciences',
        'Bachelor of Fine Arts in Photography',
        'Bachelor of Arts in Archaeology',
        'Bachelor of Science in Aerospace Engineering',
        'Bachelor of Business Administration in Accounting',
        'Bachelor of Arts in Film Studies',
        'Bachelor of Science in Geology',
        'Bachelor of International Relations',
        'Bachelor of Graphic Design',
        'Bachelor of Business Management',
        'Bachelor of Environmental Science',
        'Bachelor of Fine Arts in Acting',
        'Bachelor of Computer Engineering',
        'Bachelor of Public Administration',
        'Bachelor of Human Resource Management',
        'Bachelor of Philosophy',
        'Bachelor of Music Performance',
        'Bachelor of Software Engineering',
        'Bachelor of Media Studies',
        'Bachelor of Tourism and Hospitality Management',
        'Bachelor of Environmental Studies',
        'Bachelor of Fine Arts in Dance',
        'Bachelor of International Business Management',
        'Bachelor of Sociology and Anthropology',
        'Bachelor of Science in Neuroscience',
        'Bachelor of Arts in Political Studies',
        'Bachelor of Civil Engineering',
        'Bachelor of Communication Arts',
        'Bachelor of Health Sciences',
        'Bachelor of Industrial Design',
        'Bachelor of Applied Mathematics',
        'Bachelor of Media and Communication',
        'Bachelor of Chemical Engineering',
        'Bachelor of Public Health Administration',
        'Bachelor of Fine Arts in Sculpture',
        'Bachelor of Social Sciences in Criminology',
        'Bachelor of Materials Engineering',
        'Bachelor of Social Work and Counseling',
        'Bachelor of Data Science',
        'Bachelor of Media and Journalism',
        'Bachelor of Environmental Management',
        'Bachelor of Fine Arts in Printmaking',
        'Bachelor of Political Science and Economics',
        'Bachelor of Aerospace Engineering',
        'Bachelor of Film Production',
        'Bachelor of Biomedical Sciences',
        'Bachelor of International Development Studies',
        'Bachelor of Fine Arts in Ceramics',
        'Bachelor of Software Development',
        'Bachelor of Media Production and Communication',
        'Bachelor of Environmental Engineering Technology',
        'Bachelor of Music Composition',
        'Bachelor of Geomatics Engineering',
        'Bachelor of Anthropology and Sociology',
        'Bachelor of Social Sciences in Psychology',
        'Bachelor of Materials Science and Engineering',
        'Bachelor of Media and Public Relations',
        'Bachelor of Chemical Engineering Technology',
        'Bachelor of Public Health and Nutrition',
        'Bachelor of Fine Arts in Illustration',
        'Bachelor of Political Science and International Relations',
        'Bachelor of Civil Engineering Technology',
        'Bachelor of Communication Studies and Media',
        'Bachelor of Health Sciences Administration',
        'Bachelor of Industrial Design Engineering',
        'Bachelor of Applied Mathematics and Statistics',
        'Bachelor of Media and Cultural Studies',
        'Bachelor of Environmental Management and Sustainability',
        'Bachelor of Fine Arts in Digital Art',
        'Bachelor of Political Science and Public Policy',
        'Bachelor of Aerospace Engineering Technology',
        'Bachelor of Film Studies and Production',
        'Bachelor of Biomedical Engineering Technology',
        'Bachelor of International Relations and Diplomacy',
        'Bachelor of Fine Arts in Photography and Video',
        'Bachelor of Software Engineering Technology',
        'Bachelor of Media and Visual Arts',
        'Bachelor of Environmental Engineering and Technology',
        'Bachelor of Music and Performing Arts',
        'Bachelor of Geomatics Engineering Technology',
        'Bachelor of Anthropology and Cultural Studies',
        'Bachelor of Social Work and Human Services',
        'Bachelor of Materials Science and Technology',
        'Bachelor of Media and Entertainment Management',
        'Bachelor of Chemical Engineering and Technology',
        'Bachelor of Public Health and Epidemiology',
        'Bachelor of Fine Arts in Animation',
        'Bachelor of Political Science and Governance',
        'Bachelor of Civil Engineering and Technology',
        'Bachelor of Communication and Media Studies',
        'Bachelor of Health Sciences and Nutrition',
        'Bachelor of Industrial Design and Technology',
        'Bachelor of Applied Mathematics and Computer Science',
        'Bachelor of Media and Film Production',
        'Bachelor of Environmental Management and Conservation',
        'Bachelor of Fine Arts in Multimedia Design',
        'Bachelor of Political Science and International Development',
        'Bachelor of Aerospace Engineering and Technology',
        'Bachelor of Film Studies and Screenwriting',
        'Bachelor of Biomedical Engineering and Technology',
        'Bachelor of International Relations and Global Studies',
        'Bachelor of Fine Arts in Painting',
        'Bachelor of Software Engineering and Technology',
        'Bachelor of Media and Public Affairs',
        'Bachelor of Environmental Science and Sustainability',
        'Bachelor of Political Science and Public Administration',
        'Bachelor of Civil Engineering and Construction Management',
        'Bachelor of Communication and Journalism',
        'Bachelor of Health Sciences and Public Health',
        'Bachelor of Industrial Design and Product Development',
        'Bachelor of Applied Mathematics and Economics',
        'Bachelor of Media and Cultural Anthropology',
        'Bachelor of Environmental Engineering and Management',
        'Bachelor of Music and Sound Engineering',
        'Bachelor of Geomatics Engineering and Technology',
        'Bachelor of Anthropology and Archaeology',
        'Bachelor of Social Work and Family Studies',
        'Bachelor of Materials Science and Nanotechnology',
        'Bachelor of Media and Marketing Communications',
        'Bachelor of Chemical Engineering and Process Technology',
        'Bachelor of Public Health and Health Promotion',
        'Bachelor of Fine Arts in Film Directing',
        'Bachelor of Political Science and Conflict Resolution',
        'Master of Business Administration (MBA)',
        'Master of Science in Computer Science',
        'Master of Arts in English Literature',
        'Master of Psychology',
        'Master of Public Administration (MPA)',
        'Master of Civil Engineering',
        'Master of Science in Biology',
        'Master of Mathematics',
        'Master of History',
        'Master of Marketing',
        'Master of Mechanical Engineering',
        'Master of Environmental Science',
        'Master of Economics',
        'Master of Social Work (MSW)',
        'Master of Fine Arts in Graphic Design',
        'Master of Architecture',
        'Master of Science in Data Science',
        'Master of Public Health (MPH)',
        'Master of Education (M.Ed.)',
        'Master of Finance',
        'Master of Fine Arts in Film Production',
        'Master of International Relations',
        'Master of Physics',
        'Master of Healthcare Administration (MHA)',
    ];
    private const PASSWORD = 'admin';
    private const CAMPUSES_ADDRESSES = [
        '123 Willow Lane',
        '456 Maple Avenue',
        '789 Oak Street',
        '101 Elm Drive',
        '222 Pine Court',
        '333 Cedar Road',
        '444 Birch Lane',
        '555 Aspen Avenue',
        '666 Redwood Street',
        '777 Cypress Drive',
        '888 Spruce Court',
        '999 Juniper Road',
        '111 Magnolia Lane',
        '222 Rosewood Avenue',
        '333 Dahlia Street',
        '444 Iris Drive',
        '555 Lily Court',
        '666 Violet Road',
        '777 Petunia Lane',
        '888 Sunflower Avenue',
        '999 Orchid Street',
        '111 Tulip Drive',
        '222 Marigold Court',
        '333 Daisy Road',
        '444 Bluebell Lane',
        '555 Poppy Avenue',
        '666 Hyacinth Street',
        '777 Lily of the Valley Drive',
        '888 Peony Court',
        '999 Zinnia Road',
        '111 Snapdragon Lane',
        '222 Aster Avenue',
        '333 Buttercup Street',
        '444 Clover Drive',
        '555 Daffodil Court',
        '666 Foxglove Road',
        '777 Gardenia Lane',
        '888 Honeysuckle Avenue',
        '999 Jasmine Street',
        '111 Lavender Drive',
        '222 Marigold Court',
        '333 Narcissus Road',
        '444 Oleander Lane',
        '555 Pansy Avenue',
        '666 Quince Street',
        '777 Rose Court',
        '888 Sunflower Drive',
        '999 Tulip Lane',
        '111 Violet Avenue',
        '222 Wisteria Street',
        '333 Azalea Court',
        '444 Bluebell Road',
        '555 Camellia Lane',
        '666 Dahlia Avenue',
        '777 Elderberry Street',
        '888 Freesia Court',
        '999 Gardenia Road',
        '111 Hibiscus Lane',
        '222 Iris Avenue',
        '333 Jasmine Street',
        '444 Kangaroo Paw Drive',
        '555 Lilac Court',
        '666 Marigold Road',
        '777 Nasturtium Lane',
        '888 Orchid Avenue',
        '999 Peony Street',
        '111 Quince Court',
        '222 Rose Road',
        '333 Sunflower Lane',
        '444 Tulip Avenue',
        '555 Ulex Street',
        '666 Violet Drive',
        '777 Wisteria Court',
        '888 Xylosma Road',
        '999 Yucca Lane',
        '111 Zinnia Avenue',
        '222 Aster Street',
        '333 Begonia Drive',
        '444 Calendula Court',
        '555 Dandelion Road',
        '666 Eustoma Lane',
        '777 Fuchsia Avenue',
        '888 Geranium Street',
        '999 Holly Court',
        '111 Impatiens Drive',
        '222 Jonquil Lane',
        '333 Knapweed Avenue',
        '444 Lilium Street',
        '555 Marjoram Court',
        '666 Nigella Road',
        '777 Oleander Lane',
        '888 Peony Drive',
        '999 Quaking Grass Court',
        '111 Ranunculus Lane',
        '222 Snapdragon Avenue',
        '333 Thistle Street',
        '444 Valerian Court',
        '555 Wallflower Road',
        '666 Xylosma Lane',
        '777 Yarrow Avenue',
        '888 Zinnia Street',
        '999 Aconite Court',
        '111 Bellflower Lane',
        '222 Celandine Avenue',
        '333 Dandelion Street',
        '444 Eustoma Drive',
        '555 Freesia Court',
        '666 Gazania Road',
        '777 Heliotrope Lane',
        '888 Ixia Avenue',
        '999 Jonquil Street',
        '111 Knapweed Court',
        '222 Lily Street',
        '333 Marjoram Lane',
        '444 Nigella Avenue',
        '555 Orchid Court',
        '666 Pansy Road',
        '777 Quaking Grass Lane',
        '888 Ranunculus Avenue',
        '999 Snapdragon Street',
        '111 Thistle Court',
        '222 Valerian Lane',
        '333 Wallflower Avenue',
        '444 Xylosma Street',
        '555 Yarrow Court',
        '666 Zinnia Lane',
        '777 Aconite Avenue',
        '888 Bellflower Street',
        '999 Celandine Court',
        '111 Dandelion Lane',
        '222 Eustoma Avenue',
        '333 Freesia Street',
        '444 Gazania Court',
        '555 Heliotrope Lane',
        '666 Ixia Avenue',
        '777 Jonquil Road',
        '888 Knapweed Lane',
        '999 Lily Avenue',
        '111 Marjoram Court',
        '222 Nigella Lane',
        '333 Orchid Street',
        '444 Pansy Court',
        '555 Quaking Grass Lane',
        '666 Ranunculus Avenue',
        '777 Snapdragon Street',
        '888 Thistle Court',
        '999 Valerian Lane',
        '111 Wallflower Avenue',
        '222 Xylosma Street',
        '333 Yarrow Court',
    ];
    private const STUDENT_DATA = [
        'Emily', 'Johnson',
        'Alexander', 'Smith',
        'Olivia', 'Martinez',
        'Liam', 'Anderson',
        'Sophia', 'Brown',
        'Ethan', 'Williams',
        'Ava', 'Taylor',
        'Noah', 'Garcia',
        'Isabella', 'Clark',
        'Aiden', 'Davis',
        'Mia', 'Rodriguez',
        'Lucas', 'Wilson',
        'Harper', 'Lee',
        'Benjamin', 'Martinez',
        'Amelia', 'Thompson',
        'Elijah', 'Hall',
        'Charlotte', 'White',
        'James', 'Johnson',
        'Evelyn', 'Harris',
        'William', 'Adams',
        'Abigail', 'Scott',
        'Michael', 'Turner',
        'Sophia', 'Lewis',
        'Daniel', 'Young',
        'Grace', 'King',
        'Matthew', 'Martinez',
        'Ava', 'Green',
        'Logan', 'Wright',
        'Olivia', 'Rodriguez',
        'Jackson', 'Mitchell',
        'Emma', 'Walker',
        'Lucas', 'Hill',
        'Mia', 'Carter',
        'Ethan', 'Brown',
        'Isabella', 'Cooper',
        'Alexander', 'Turner',
        'Harper', 'Bennett',
        'Benjamin', 'Flores',
        'Amelia', 'Reed',
        'Liam', 'Morgan',
        'Ava', 'Collins',
        'Noah', 'Foster',
        'Emily', 'Murphy',
        'William', 'Rivera',
        'Charlotte', 'Powell',
        'James', 'Ward',
        'Sophia', 'Adams',
        'Jacob', 'Jenkins',
        'Olivia', 'Butler',
        'Mia', 'Parker',
    ];

    public function __construct(
        private readonly StudentUserCreator $studentCreator,
        private readonly PasswordHasherFactoryInterface $hasherFactory,
        private readonly UuidGenerator $uuidGenerator,
    ) {
    }

    public function createEntities(): array
    {
        $entities = [];
        $applicationsData = [];
        $now = new \DateTimeImmutable();
        $nowPlus2years = clone $now->add(new \DateInterval('P3Y'));
        $dateOfBirth = \DateTimeImmutable::createFromFormat('Y-m-d', '1990-01-01');
        $campusIndex = 0;
        $coursesCount = count(self::COURSES);
        foreach (self::SCHOOL_NAMES as $index => $name) {
            $adminNameAndSurname = explode(' ', self::ADMIN_NAMES[$index]);
            $email = str_replace(' ', '.', strtolower($name)) . '@example.com';

            $school = School::register(
                new SchoolId($this->uuidGenerator->generate()),
                new Name($name),
                new StaffMemberId($this->uuidGenerator->generate()),
                new StaffMemberName($adminNameAndSurname[0], $adminNameAndSurname[1]),
                new Email($email),
                $this->buildCreatedAt($now, $index % 2 === 0 ? 'M':'D')
            );
            $school->confirmRegister(
                new InvitationToken(
                    $this->uuidGenerator->generate(),
                    new \DateTimeImmutable()
                )
            );
            $school->getAdmin()->confirmAccount(
                $this->hasherFactory->getPasswordHasher(StaffMember::class)
                    ->hash(self::PASSWORD)
            );
            $campus = new Campus(
                $school->getId(),
                new CampusId($this->uuidGenerator->generate()),
                self::CAMPUSES_NAMES[$campusIndex],
                self::CAMPUSES_ADDRESSES[$campusIndex],
            );
            ++$campusIndex;
            if ($index % 2 === 0) {
                $campus2 = new Campus(
                    $school->getId(),
                    new CampusId($this->uuidGenerator->generate()),
                    self::CAMPUSES_NAMES[$campusIndex],
                    self::CAMPUSES_ADDRESSES[$campusIndex],
                );
                ++$campusIndex;
                $entities[] = $campus2;
            }
            $courseIndexes = [];
            while (count($courseIndexes) < 20) {
                $courseIndex = rand(0, $coursesCount - 1);
                $courseIndexes[$courseIndex] = true;
            }
            $courseIndexes = array_keys($courseIndexes);
            foreach ($courseIndexes as $courseIndex) {
                $course = new Course(
                    $school->getId(),
                    new CourseId($this->uuidGenerator->generate()),
                    self::COURSES[$courseIndex],
                );
                $daysTillStart = rand(50, 365 * 2);
                $start = $now->add(new \DateInterval("P{$daysTillStart}D"));
                $durationDays = rand(365, 365 * 3);
                $end = $start->add(new \DateInterval("P{$durationDays}D"));
                $intake = $course->addIntake(
                    new IntakeId($this->uuidGenerator->generate()),
                    $start,
                    $end,
                    rand(0, 1) === 0 ? 'Thesis' : 'Full-time',
                    rand(5, 50)
                );
                $applicationsData[] = [$intake, $school, $course];
                $entities[] = $course;
            }
            $entities[] = $school;
            $entities[] = $campus;
        }

        for ($j = 0; $j < 20; $j++) {
            $intake = $applicationsData[$j][0];
            $data = self::STUDENT_DATA[$j];
            $application = new Application(
                new ApplicationId($this->uuidGenerator->generate()),
                $student = $this->studentCreator->create(
                    $data[0],
                    $data[1],
                    strtolower($data[0] . $data[1] . '@example.com')
                ),
                $applicationsData[$j][1],
                $applicationsData[$j][2],
                $intake,
                '123456',
                $nowPlus2years,
                $dateOfBirth,
                $data[0] . ' ' . $data[1],
                null,
                $this->buildCreatedAt($now, 'D')
            );
            $entities[] = $student;
            $entities[] = $application;
        }

        return $entities;
    }

    private function buildCreatedAt(\DateTimeImmutable $now, $subType='M'): \DateTimeImmutable
    {
        $registerDay = rand(1, 28);
        $registerMonth = rand(1, 12);
        $createdAt = \DateTimeImmutable::createFromFormat(
            'Y-m-d',
            $now->format('Y-m-') . $registerDay
        )
            ->sub(new \DateInterval("P{$registerMonth}{$subType}"));
        return $createdAt > $now ? clone $now : $createdAt;
    }
}
