doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            !php/const App\Core\School\Entity\School\SchoolIdType::NAME: 'App\Core\School\Entity\School\SchoolIdType'
            !php/const App\Core\Admin\Entity\AdminUser\AdminUserIdType::NAME: 'App\Core\Admin\Entity\AdminUser\AdminUserIdType'
            !php/const App\Core\School\Entity\School\StaffMemberIdType::NAME: 'App\Core\School\Entity\School\StaffMemberIdType'
            !php/const App\Core\School\Entity\Campus\CampusIdType::NAME: 'App\Core\School\Entity\Campus\CampusIdType'
            !php/const App\Core\School\Entity\Course\CourseIdType::NAME: 'App\Core\School\Entity\Course\CourseIdType'
            !php/const App\Core\School\Entity\Course\Intake\IntakeIdType::NAME: 'App\Core\School\Entity\Course\Intake\IntakeIdType'
            !php/const App\Core\Student\Entity\Student\StudentIdType::NAME: 'App\Core\Student\Entity\Student\StudentIdType'
            !php/const App\Core\Student\Entity\Application\ApplicationIdType::NAME: 'App\Core\Student\Entity\Application\ApplicationIdType'

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            School:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/School/Entity'
                prefix: 'App\Core\School\Entity'
                alias: School
            Student:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Student/Entity'
                prefix: 'App\Core\Student\Entity'
                alias: Student
            Admin:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Admin/Entity'
                prefix: 'App\Core\Admin\Entity'
                alias: Admin

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
