security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Security\Admin\AdminReadModel:
            algorithm: auto
        App\Security\School\SchoolStaffMemberReadModel:
            algorithm: auto
        App\Security\Student\StudentReadModel:
            algorithm: auto
        App\Core\Admin\Entity\AdminUser\AdminUser:
            algorithm: auto
        App\Core\School\Entity\School\StaffMember:
            algorithm: auto
        App\Core\Student\Entity\Student\Student:
            algorithm: auto
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        admin_user_provider:
            id: App\Security\Admin\AdminProvider
        school_user_provider:
            id: App\Security\School\SchoolStaffMemberProvider
        student_user_provider:
            id: App\Security\Student\StudentProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        school:
            lazy: true
            provider: school_user_provider
            pattern: ^/(api\/)?school
            custom_authenticator: App\Security\School\SchoolStaffMemberAuthenticator
            logout:
                path: school_logout
                target: school_login
                invalidate_session: false
        student:
            lazy: true
            pattern: ^/(api\/)?student
            provider: student_user_provider
            custom_authenticator: App\Security\Student\StudentAuthenticator
            user_checker: App\Security\Student\StudentChecker
            logout:
                path: !php/const App\Infrastructure\RouteEnum::STUDENT_LOGOUT
                target: !php/const App\Infrastructure\RouteEnum::STUDENT_LOGIN
                invalidate_session: false
        admin:
            lazy: true
            custom_authenticator: App\Security\Admin\AdminAuthenticator
            provider: admin_user_provider
            logout:
                path: !php/const App\Infrastructure\RouteEnum::ADMIN_LOGOUT
                target: !php/const App\Infrastructure\RouteEnum::ADMIN_LOGIN
                invalidate_session: false

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SCHOOL_ADMIN
            - ROLE_SCHOOL_USER
        ROLE_SCHOOL_ADMIN:
            - ROLE_SCHOOL_USER
            - ROLE_USER
        ROLE_STUDENT_USER:
            - ROLE_USER

    access_control:
        - { route: !php/const App\Infrastructure\RouteEnum::HOME, roles: PUBLIC_ACCESS }
        - { route: !php/const App\Infrastructure\RouteEnum::STUDENT_LOGIN, roles: PUBLIC_ACCESS }
        - { route: !php/const App\Infrastructure\RouteEnum::ADMIN_LOGIN, roles: PUBLIC_ACCESS }
        - { route: !php/const App\Infrastructure\RouteEnum::SCHOOL_LOGIN, roles: PUBLIC_ACCESS }
        - { route: school_member_register, roles: PUBLIC_ACCESS }
        - { route: !php/const App\Infrastructure\RouteEnum::SCHOOL_REGISTER, roles: PUBLIC_ACCESS }
        - { route: !php/const App\Infrastructure\RouteEnum::STUDENT_REGISTER, roles: PUBLIC_ACCESS }
        - { route: !php/const App\Infrastructure\RouteEnum::STUDENT_VERIFY_EMAIL, roles: PUBLIC_ACCESS }

        - { path: ^/(api\/)?school, roles: ROLE_SCHOOL_ADMIN }
        - { path: ^/(api\/)?student, roles: ROLE_STUDENT_USER }
        - { path: ^/(api\/)?admin, roles: ROLE_ADMIN }
        - { path: .*, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
