twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        google_tag_manager_id: '%env(GOOGLE_TAG_MANAGER_ID)%'

when@test:
    twig:
        strict_variables: true
