name: Test CI

on:
  push:
    branches: [ "test-ci" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Validate composer files
      run: make validate
