name: Push

on:
  workflow_dispatch:
  push:
    branches: [ "test-ci" ]

env:
  REGISTRY_HOST: ghcr.io
  REGISTRY: ghcr.io/${{ github.repository }}
  IMAGE_TAG: master-${{ github.run_number }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_HOST }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: build
      run: make ci-build
    - name: push
      run: make ci-push

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Up
        run: make ci-up
      - name: Db
        run: make ci-db
      - name: Run acceptance tests
        run: make ci-tests-a

  validate:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Validate composer files
      run: make ci-validate
    - name: Validate php code style
      run: make ci-code-style-check-php


