name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ "test-ci" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Validate composer files
      run: make validate
    - name: Init
      run: TEST_START_XVFB=false make tests-init
    - name: Run acceptance tests
      run: TEST_HEADLESS=-headless make tests-a

