name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ "test-ci" ]

jobs:

  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Validate composer files
      run: make validate
    - name: Init
      run: make tests-init
    - name: Run acceptance tests
      run: make tests-a

